global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'user-service'
    static_configs:
      - targets: ['python-user-service:8000']

  - job_name: 'order-service'
    static_configs:
      - targets: ['rust-order-service:8001']

  - job_name: 'inventory-service'
    static_configs:
      - targets: ['go-inventory-service:8002']
